---


- name: update cahce
  apt:
    update_cache: yes

- name: upgrade packages
  apt:
    upgrade: dist

- name: install packages
  apt:
    name:
      - git
      - ufw
      - ca-certificates 
      - curl
    state: present

- name: download gpg for Docker
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: update cahce
  apt:
    update_cache: yes

- name: install Docker 
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: adding user to Docker group
  command: usermod -aG docker {{ ansible_user }}
